### ISSUE TITLE
Update pyro-api interaction workflow

### ISSUE THREAD

**Issue by fe51** [pyronear/pyro-engine#43] opened 2021-05-16 20:23 UTC
The webserver (via [engine.py](https://github.com/pyronear/pyro-engine/blob/master/pyroengine/engine/engine.py))  interactions with pyro-api is not up to date.

There have been some updates pyro-api side about about alerts/events workflow. 
It has to be managed in in pyro-engine.

Also, remember that an instance of the client's class is used for each pi camera (in order to identify from which pi the sent information comes from).

With #31, picamera using inference route will be authenticated. Hence, the right instance of pyro-client has to be used. (I would  suggest to instantiate a dict containing authenticated class for each pi in a dict created at the start up of the webserver)
Credentials of picamera on pyro-api could be stored in the `fleet_access.json` file (see #31)

Sorry if this issue is not detailed enough yet, lack of time on my side,
Would be happy to discuss it,
Thanks a lot

**Comment by frgfm** [comment] 2022-08-03 18:12
Isn't this a duplicate of #51 ? :thinking:  (or the other way haha)

**Comment by fe51** [comment] 2022-08-04 06:23
Well so far, we have succeed to manage the worklfow with pyro-api. Hence, unless we want to question it now, this issue should be closed.

**Closed** 2022-08-04 06:23 UTC
Labels: duplicate, topic: ci, ext: tests
